<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>scoutcar_bringup</name>
  <version>0.1.0</version>
  <description>CityScout 全车节点启动与参数配置</description>
  <maintainer email="orangepi@example.com">orangepi</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>scoutcar_camera</exec_depend>
  <exec_depend>scoutcar_perception</exec_depend>
  <exec_depend>scoutcar_planning</exec_depend>
  <exec_depend>scoutcar_control</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
