front_camera_node:
  ros__parameters:
    camera_path: "/dev/video31"
    fps: 30
    image_width: 640
    image_height: 480
    image_topic: "/camera/front/image_raw"
    health_topic: "/camera/front/healthy"
    prefer_mipi: true
    rotate_180: false
    
turn_camera_node:
  ros__parameters:
    camera_path: "/dev/video22"
    fps: 30
    image_width: 640
    image_height: 480
    image_topic: "/camera/turn/image_raw"
    health_topic: "/camera/turn/healthy"
    prefer_mipi: true
    rotate_180: true

perception_node:
  ros__parameters:
    enable_turning_inference: true

    ipm.front_source_points: [269.0, 190.0, 414.0, 190.0, 142.0, 400.0, 544.0, 400.0]
    ipm.turn_left_source_points: [270.0, 190.0, 381.0, 190.0, 130.0, 420.0, 451.0, 420.0]
    ipm.turn_right_source_points: [290.0, 190.0, 409.0, 190.0, 210.0, 420.0, 536.0, 420.0]
    ipm.front_destination_points: [190.0, 190.0, 450.0, 190.0, 190.0, 470.0, 450.0, 470.0]
    ipm.turn_left_destination_points: [190.0, 120.0, 450.0, 120.0, 190.0, 470.0, 450.0, 470.0]
    ipm.turn_right_destination_points: [190.0, 120.0, 450.0, 120.0, 190.0, 470.0, 450.0, 470.0]

    road_tracking.scan_end_y: 120
    road_tracking.min_road_width_px: 225
    road_tracking.max_road_width_px: 285
    road_tracking.min_barrier_width_px: 12
    road_tracking.search_expand_px: 20
    road_tracking.min_valid_rows: 60
    
    road_tracking.front_reference_x: 315
    road_tracking.turn_left_reference_x: 365
    road_tracking.turn_right_reference_x: 301

    detect.confidence_threshold: 0.8
    detect.nms_threshold: 0.45


mission_node:
  ros__parameters:
    turn_penalty: 0.5
    u_turn_penalty: 1.0
    tunnel_risk: 0.0
    route_mode: "auto"
    route_nodes: [
      1,3,2,6,7,11,10,14,15,19,18,14,15,11,10,6,7,8,12,11,7,6,5,9,10,14,15,11,12,16,15,14,10,9,13,14,18,19,20,16,15,11,10,6,7,4,3,1
    ]

serial_node:
  ros__parameters:
    serial_device: "/dev/ttyS6"
    deviation_rate_hz: 30.0
    deviation_timeout_ms: 150
    baud_rate: 115200
