front_camera_node:
  ros__parameters:
    camera_path: "/dev/video31"
    fps: 30
    image_width: 640
    image_height: 480
    image_topic: "/camera/front/image_raw"
    prefer_mipi: true

turn_camera_node:
  ros__parameters:
    camera_path: "/dev/video22"
    fps: 30
    image_width: 640
    image_height: 480
    image_topic: "/camera/turn/image_raw"
    prefer_mipi: true

perception_node:
  ros__parameters:
    ipm.front_source_points: [232.0, 190.0, 431.0, 190.0, 95.0, 420.0, 588.0, 420.0]
    ipm.turn_source_points: [260.0, 190.0, 400.0, 190.0, 145.0, 420.0, 520.0, 420.0]
    ipm.front_destination_points: [180.0, 120.0, 460.0, 120.0, 180.0, 470.0, 460.0, 470.0]
    ipm.turn_destination_points: [170.0, 120.0, 470.0, 120.0, 170.0, 470.0, 470.0, 470.0]

    road_tracking.scan_end_y: 120
    road_tracking.min_road_width_px: 225
    road_tracking.max_road_width_px: 285
    road_tracking.min_barrier_width_px: 12
    road_tracking.search_expand_px: 20
    road_tracking.min_valid_rows: 60
    road_tracking.front_reference_x: 312
    road_tracking.turn_reference_x: 320

    detect.confidence_threshold: 0.25
    detect.nms_threshold: 0.45


mission_node:
  ros__parameters:
    turn_penalty: 0.5
    u_turn_penalty: 1.0
    tunnel_risk: 0.0
    obstacle_mode: "bidirectional"

serial_node:
  ros__parameters:
    serial_device: "/dev/ttyS6"
    deviation_rate_hz: 30.0
    deviation_timeout_ms: 150
    baud_rate: 115200
